### ISSUE TITLE
Using ignore missing in include causes TwigException

### ISSUE THREAD

**Issue by mattbanks** [PKuebler/metalsmith-twig#10]
Getting an error when trying to use `ignore missing` in an include instead a template.

Here's the call I'm using:

`{% include '_partials/my_partial_file.twig' ignore missing %}`

When I try to run a build, I get the following errors:

```
Error compiling twig template /Users/my_user/my_project_dir/views/my_view.twig:
TwigException: Twig.expression.type.variable cannot follow a Twig.expression.type.variable at template:10 near 'ignore...'
Error parsing twig template /Users/my_user/my_project_dir/views/my_view.twig:
TypeError: Cannot read property 'forEach' of undefined
    at Object.Twig.forEach (/Users/my_user/my_project_dir/node_modules/twig/twig.min.js:8:821)
    at Twig.parse (/Users/my_user/my_project_dir/node_modules/twig/twig.min.js:8:11203)
    at Twig.Template.render (/Users/my_user/my_project_dir/node_modules/twig/twig.min.js:8:16150)
    at load (/Users/my_user/my_project_dir/node_modules/metalsmith-twig/lib/index.js:45:42)
    at loadTemplateFn (/Users/my_user/my_project_dir/node_modules/twig/twig.min.js:8:20154)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
buffer.js:259
  throw new TypeError(kFromErrorMsg);
  ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:259:9)
    at Function.Buffer.from (buffer.js:96:10)
    at new Buffer (buffer.js:75:17)
    at load (/Users/my_user/my_project_dir/node_modules/metalsmith-twig/lib/index.js:45:22)
    at loadTemplateFn (/Users/my_user/my_project_dir/node_modules/twig/twig.min.js:8:20154)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

Taking out `ignore missing` gives a successful build, but there will be cases where I'm looping through things and an include for a particular file might not exist. Any thoughts on getting this to work, or a workaround?

**Comment by mattbanks** [comment]
Figured out that Twig.js needs `ignore missing` before the file name.

`{% include ignore missing '_partials/my_partial_file.twig' %}`
