### ISSUE TITLE
Error compiling Twig templates with v1.1.0

### ISSUE THREAD

**Issue by mattbanks** [PKuebler/metalsmith-twig#11]
Our builds started failing on our Jenkins server last night with the only change being v1.1.0 of metalsmith-twig getting installed with the `npm install` run.

```
06:18:49 > cross-env NODE_ENV=development node index.js 2>&1 | tee output.log
06:18:49 
06:18:57 Error compiling twig template /jenkins/workspace/myProjectName/views/explore.twig: 
06:18:57 TwigException: Twig.expression.type.variable cannot follow a Twig.expression.type.variable at template:6 near 'missing...'
06:18:57 /jenkins/workspace/myProjectName/node_modules/twig/twig.js:7514
06:18:57 	            if (index == arr.length) {
06:18:57 	                            ^
06:18:57 
06:18:57 TypeError: Cannot read property 'length' of undefined
06:18:57     at iterate (/jenkins/workspace/myProjectName/node_modules/twig/twig.js:7514:30)
06:18:57     at Object.forEachAsync [as forEach] (/jenkins/workspace/myProjectName/node_modules/twig/twig.js:7522:10)
06:18:57     at Twig.parse (/jenkins/workspace/myProjectName/node_modules/twig/twig.js:875:31)
06:18:57     at Twig.parseAsync (/jenkins/workspace/myProjectName/node_modules/twig/twig.js:7313:28)
06:18:57     at Twig.Template.render (/jenkins/workspace/myProjectName/node_modules/twig/twig.js:1379:36)
06:18:57     at load (/jenkins/workspace/myProjectName/node_modules/metalsmith-twig/lib/index.js:54:42)
06:18:57     at loadTemplateFn (/jenkins/workspace/myProjectName/node_modules/twig/twig.js:5726:18)
06:18:57     at tryToString (fs.js:456:3)
06:18:57     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
```

We rolled back and locked `metalsmith-twig` at 1.0.4 for now, but I'd like to look into what happened. It seems like the only changes are upstream package bumps to twig and async. Possibly a breaking change upstream there?

Our metalsmith config uses this for the twig config:

```
  .use(twig({
    directory: 'views',
    cache: false
  }))
```

**Comment by PKuebler** [comment]
hey,

thanks for your feedback.

I have added your scenario to the test ( dd95f22533e327a368b100721defc723866830ee ) and got no errors. I also find the line in the `vendor` of twig.js not.

can you tell me which twig functions do you use? so `for`, `include`, `extends`, `block`, ...

**Comment by mattbanks** [comment]
Here's the line 6 of the explore.twig template where I believe it's giving the error:

```
{% for module in hero_modules %}
    {% set moduleFile = '../_temp/modules/' ~ module|lower ~ '/index_' ~ locale ~ '.json' %}
    {% include ignore missing moduleFile with { "echelon": loop.index0 } %}{{ loop.last ? "" : "," }}
{% endfor %}
```

It's part of the `include` statement, I believe.

**Comment by PKuebler** [comment]
I have reconstructed the error.

he only comes with `ignore missing`. if I move this comes the error no more. 

```
{% for module in hero_modules %}
    {% set moduleFile = '../_temp/modules/' ~ module|lower ~ '/index_' ~ locale ~ '.json' %}	
    {% include moduleFile ignore missing with { "echelon": loop.index0 } %}{{ loop.last ? "" : "," }}
{% endfor %}
```

can you try this out? twig.js seems to have changed there.

**Comment by mattbanks** [comment]
Oh nice - thanks @PKuebler! I'm out for a long weekend, but I'll give this a shot on Monday and let you know how it goes!

**Comment by PKuebler** [comment]
can you tell me more?

**Comment by mattbanks** [comment]
@PKuebler sorry, last week got crazy busy. I'm planning on testing the change on Monday/Tuesday this week and will get back to you as soon as I can!

**Comment by mattbanks** [comment]
Tried making the change this morning, but I get further errors because of the `with` statements. It doesn't like that being after `ignore missing`. Tried putting `ignore missing` after the `with` statement, but it doesn't seem to like that either.

```
Error compiling twig template /Users/mbanks/Code/myProjectName/views/explore.twig:
TwigException: Twig.expression.type.variable cannot follow a Twig.expression.type.object.end at template:23 near 'ignore...'
/Users/mbanks/Code/myProjectName/node_modules/metalsmith-twig/node_modules/twig/twig.js:7514
	            if (index == arr.length) {
	                             ^

TypeError: Cannot read property 'length' of undefined
    at iterate (/Users/mbanks/Code/myProjectName/node_modules/metalsmith-twig/node_modules/twig/twig.js:7514:31)
    at Object.forEachAsync [as forEach] (/Users/mbanks/Code/myProjectName/node_modules/metalsmith-twig/node_modules/twig/twig.js:7522:10)
    at Twig.Template.Twig.parse (/Users/mbanks/Code/myProjectName/node_modules/metalsmith-twig/node_modules/twig/twig.js:875:31)
    at Twig.Template.Twig.parseAsync (/Users/mbanks/Code/myProjectName/node_modules/metalsmith-twig/node_modules/twig/twig.js:7313:28)
    at Twig.Template.render (/Users/mbanks/Code/myProjectName/node_modules/metalsmith-twig/node_modules/twig/twig.js:1379:36)
    at load (/Users/mbanks/Code/myProjectName/node_modules/metalsmith-twig/lib/index.js:56:42)
    at loadTemplateFn (/Users/mbanks/Code/myProjectName/node_modules/metalsmith-twig/node_modules/twig/twig.js:5726:18)
    at tryToString (fs.js:514:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:502:12)
```

**Comment by PKuebler** [comment]
Sorry,
i have no idea.

i use only the twig.js package. Maybe you'll make an issue there?

https://github.com/twigjs/twig.js
